# Generated by Django 6.0.3 on 2026-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
